<a href="https://colab.research.google.com/github/RenChina/MachLearn12/blob/main/lab1_numpyBabenko.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np

2) Создать нулевой вектор размера 10

In [ ]:
zero_vector = np.zeros(10)

In [ ]:
zero_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
sevens_vector = np.full(7, 7)

In [ ]:
sevens_vector

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
even_vector = np.arange(10, 101, 2)

In [ ]:
even_vector

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
random_array = np.random.rand(10)

In [ ]:
random_array

array([0.46954847, 0.82933502, 0.60252527, 0.51666489, 0.62034066,
       0.57522132, 0.42922403, 0.05800642, 0.83487425, 0.2975772 ])

In [ ]:
reversed_array = random_array[::-1]

In [ ]:
reversed_array

array([0.2975772 , 0.83487425, 0.05800642, 0.42922403, 0.57522132,
       0.62034066, 0.51666489, 0.60252527, 0.82933502, 0.46954847])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)

In [ ]:
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
offset_identity = np.eye(4, k=1)

In [ ]:
offset_identity

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
diag_sevens_matrix = np.full((4, 4), 7)

In [ ]:
diag_sevens_matrix

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.fill_diagonal(diag_sevens_matrix, np.arange(1, 5))

In [ ]:
diag_sevens_matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
row_repeat_matrix = np.tile(np.arange(5), (5, 1))

In [ ]:
row_repeat_matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
random_matrix_10x10 = np.random.rand(10, 10)

In [ ]:
random_matrix_10x10

array([[0.76935116, 0.87897989, 0.52411864, 0.01139714, 0.60005081,
        0.01290434, 0.16984002, 0.65981613, 0.79148031, 0.65718008],
       [0.59172673, 0.5977947 , 0.21383033, 0.44003294, 0.56466168,
        0.44973914, 0.92826353, 0.54191202, 0.00331349, 0.21543322],
       [0.08466066, 0.01959679, 0.8234007 , 0.9472867 , 0.8031956 ,
        0.99095359, 0.63412634, 0.07579534, 0.80293125, 0.91850004],
       [0.64611094, 0.12303028, 0.95110045, 0.52529041, 0.01431197,
        0.99671234, 0.88387841, 0.26041   , 0.44075256, 0.86004419],
       [0.44450284, 0.76459102, 0.05802043, 0.98241105, 0.13501815,
        0.59341044, 0.84680483, 0.95413414, 0.28060496, 0.46956821],
       [0.70512126, 0.44172223, 0.71916914, 0.47910493, 0.67945502,
        0.07429508, 0.65815498, 0.24673989, 0.21880601, 0.27657495],
       [0.02384114, 0.142543  , 0.48688503, 0.8086702 , 0.45134787,
        0.90844655, 0.83214785, 0.03575624, 0.39041108, 0.33569779],
       [0.81184328, 0.30486882, 0.6200999

In [ ]:
mean_subtracted_matrix = random_matrix_10x10 - random_matrix_10x10.mean(axis=1, keepdims=True)

In [ ]:
mean_subtracted_matrix

array([[ 0.26183931,  0.37146804,  0.01660679, -0.49611471,  0.09253896,
        -0.49460752, -0.33767183,  0.15230427,  0.28396846,  0.14966823],
       [ 0.13705595,  0.14312392, -0.24084045, -0.01463784,  0.1099909 ,
        -0.00493164,  0.47359276,  0.08724124, -0.45135729, -0.23923756],
       [-0.52538404, -0.59044791,  0.213356  ,  0.337242  ,  0.1931509 ,
         0.38090889,  0.02408164, -0.53424936,  0.19288655,  0.30845534],
       [ 0.07594678, -0.44713387,  0.3809363 , -0.04487375, -0.55585218,
         0.42654818,  0.31371426, -0.30975416, -0.12941159,  0.28988003],
       [-0.10840377,  0.21168441, -0.49488618,  0.42950444, -0.41788846,
         0.04050383,  0.29389822,  0.40122753, -0.27230165, -0.08333839],
       [ 0.25520691, -0.00819212,  0.26925479,  0.02919059,  0.22954067,
        -0.37561927,  0.20824063, -0.20317446, -0.23110834, -0.1733394 ],
       [-0.41773354, -0.29903167,  0.04531035,  0.36709553,  0.00977319,
         0.46687188,  0.39057318, -0.40581844

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
median_subtracted_matrix = random_matrix_10x10 - np.median(random_matrix_10x10, axis=0)

In [ ]:
median_subtracted_matrix

array([[ 0.16358465,  0.50568437,  0.01861681, -0.49080053,  0.06592356,
        -0.71966506, -0.47630063,  0.1629908 ,  0.2720015 ,  0.17405767],
       [-0.01403979,  0.22449918, -0.2916715 , -0.06216473,  0.03053443,
        -0.28283026,  0.28212287,  0.04508669, -0.51616533, -0.26768919],
       [-0.52110586, -0.35369873,  0.31789886,  0.44508903,  0.26906836,
         0.2583842 , -0.01201432, -0.42102998,  0.28345243,  0.43537763],
       [ 0.04034442, -0.25026524,  0.44559862,  0.02309274, -0.51981527,
         0.26414294,  0.23773775, -0.23641533, -0.07872625,  0.37692178],
       [-0.16126367,  0.3912955 , -0.4474814 ,  0.48021338, -0.3991091 ,
        -0.13915895,  0.20066417,  0.45730881, -0.23887385, -0.01355419],
       [ 0.09935475,  0.0684267 ,  0.2136673 , -0.02309274,  0.14532777,
        -0.65827431,  0.01201432, -0.25008544, -0.3006728 , -0.20654746],
       [-0.58192538, -0.23075252, -0.01861681,  0.30647253, -0.08277938,
         0.17587716,  0.18600719, -0.46106909

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.

> Добавить блок с цитатой



In [ ]:
matrix = np.random.rand(5, 5)
row_max = np.max(matrix, axis=1).reshape(-1, 1)
row_min = np.min(matrix, axis=1).reshape(-1, 1)
new_matrix = np.hstack((matrix, row_max, row_min))


In [ ]:
new_matrix

array([[0.62941503, 0.58064476, 0.99494005, 0.51441699, 0.19171725,
        0.99494005, 0.19171725],
       [0.48600436, 0.88107597, 0.29240558, 0.65912114, 0.60183474,
        0.88107597, 0.29240558],
       [0.29621323, 0.18103659, 0.85189716, 0.23640351, 0.05774191,
        0.85189716, 0.05774191],
       [0.45361518, 0.93784265, 0.90558108, 0.99873853, 0.72742545,
        0.99873853, 0.45361518],
       [0.74624535, 0.32883622, 0.13395188, 0.57093484, 0.02196555,
        0.74624535, 0.02196555]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
vector = np.arange(1, 52)

odd_numbers = vector[vector % 2 != 0]
even_numbers = vector[vector % 2 == 0]

odd_matrix = odd_numbers.reshape(-1, 1)
even_matrix = even_numbers.reshape(1, -1)

product_matrix = np.dot(odd_matrix, even_matrix)

try:
    inverse_matrix = np.linalg.inv(product_matrix)
    print("Обратная матрица:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Матрица необратима (определитель равен нулю)")

print("Матрица из нечетных чисел:\n", odd_matrix)
print("Матрица из четных чисел:\n", even_matrix)
print("Произведение матриц:\n", product_matrix)

Матрица необратима (определитель равен нулю)
Матрица из нечетных чисел:
 [[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]
 [21]
 [23]
 [25]
 [27]
 [29]
 [31]
 [33]
 [35]
 [37]
 [39]
 [41]
 [43]
 [45]
 [47]
 [49]
 [51]]
Матрица из четных чисел:
 [[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]
Произведение матриц:
 [[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288  306  324  342  360  378  396  414  4

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
chessboard = np.zeros((8, 8), dtype=int)

chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print("Шахматная матрица 8x8:\n", chessboard)

Шахматная матрица 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
